apiVersion: v1
kind: Service
metadata:
  name: adminer-web-lb
  labels:
    kubernetes.courselabs.co: statefulsets
spec:
  ports:
    - port: 8020
      targetPort: 8080
  selector:
    app: adminer-web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-web-np
  labels:
    kubernetes.courselabs.co: statefulsets
spec:
  ports:
    - port: 8020
      targetPort: 8080
      nodePort: 30020
  selector:
    app: adminer-web
  type: NodePort