apiVersion: v1
kind: Service
metadata:
  name: products-api
  labels:
    kubernetes.courselabs.co: hackathon
    app: widgetario
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: widgetario
    component: products-api
  type: ClusterIP