apiVersion: v1
kind: Secret
metadata:
  name: products-api-db
  labels:
    kubernetes.courselabs.co: hackathon
type: Opaque
stringData:
  application.properties: |-
    spring.jpa.database=POSTGRESQL
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://products-db-0.products-db.default.svc.cluster.local:5432/postgres
    spring.datasource.username=postgres
    spring.datasource.password=h4ckkath0n