apiVersion: v1
kind: Secret
metadata:
  name: stock-api-connection
  labels:
    kubernetes.courselabs.co: hackathon
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "host=products-db-1.products-db.default.svc.cluster.local port=5432 user=postgres password=h4ckkath0n dbname=postgres sslmode=disable"
