apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: infra
  labels:
    team: infrastructure
spec:
  ports:
  - port: 1234
    targetPort: buildkitd
  selector:
    app: buildkitd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: infra
  labels:
    team: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      automountServiceAccountToken: false
      containers:
      - name: buildkitd
        image: moby/buildkit:v0.9.0
        args:
          - --addr
          - unix:///run/buildkit/buildkitd.sock
          - --addr
          - tcp://0.0.0.0:1234
        securityContext:
          privileged: true
        ports:
          - name: buildkitd
            containerPort: 1234