# common config
domainName: widgetario.local
includeReadiness: true
includeLiveness: true
includeResources: true

# Products API ("papi")
papiImage: widgetario/products-api:21.03
papiReplicaCount: 2

# Products database ("pdb")
pdbImage: widgetario/products-db-replicated:21.03
pdbReplicaCount: 2
pdbStorageSize: 50Mi
pdbUsername: postgres
pdbPassword: h4kka7h_n

# Stock API ("sapi")
sapiImage: widgetario/stock-api:21.03
sapiReplicaCount: 4

# Website ("web")
webLoggerImage: alpine:3.14
webReplicaCount: 2
webTheme: dark
webImage: widgetario/web:21.03