apiVersion: v1
kind: Service
metadata:
  name: simple-proxy-lb
  labels:
    kubernetes.courselabs.co: statefulsets
spec:
  ports:
    - port: 8040
      targetPort: 80
  selector:
    app: simple-proxy
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: simple-proxy-np
  labels:
    kubernetes.courselabs.co: statefulsets
spec:
  ports:
    - port: 8040
      targetPort: 80
      nodePort: 30040
  selector:
    app: simple-proxy
  type: NodePort